export const dummyData = {
  classrooms: [
    {
      id: 1,
      name: "Room 101",
      capacity: 60,
      type: "Lecture Hall",
      building: "Block A",
      floor: 1,
      facilities: ["Projector", "WiFi", "Air Conditioning", "Whiteboard"],
    },
    {
      id: 2,
      name: "Lab 201",
      capacity: 30,
      type: "Laboratory",
      building: "Block B",
      floor: 2,
      facilities: ["Computers", "WiFi", "Air Conditioning", "Smart Board"],
    },
    {
      id: 3,
      name: "Seminar Hall 301",
      capacity: 40,
      type: "Seminar Room",
      building: "Block C",
      floor: 3,
      facilities: ["Projector", "WiFi", "Sound System", "Whiteboard"],
    },
    {
      id: 4,
      name: "Auditorium",
      capacity: 200,
      type: "Lecture Hall",
      building: "Main Block",
      floor: 1,
      facilities: ["Projector", "Sound System", "Air Conditioning", "Stage"],
    },
    {
      id: 5,
      name: "Room 102",
      capacity: 50,
      type: "Lecture Hall",
      building: "Block A",
      floor: 1,
      facilities: ["Projector", "WiFi", "Whiteboard"],
    },
    {
      id: 6,
      name: "Computer Lab 202",
      capacity: 35,
      type: "Computer Lab",
      building: "Block B",
      floor: 2,
      facilities: ["Computers", "WiFi", "Air Conditioning", "Smart Board", "Printers"],
    },
    {
      id: 7,
      name: "Physics Lab 203",
      capacity: 25,
      type: "Laboratory",
      building: "Block B",
      floor: 2,
      facilities: ["Lab Equipment", "WiFi", "Safety Equipment"],
    },
    {
      id: 8,
      name: "Room 401",
      capacity: 45,
      type: "Lecture Hall",
      building: "Block D",
      floor: 4,
      facilities: ["Projector", "WiFi", "Air Conditioning", "Smart Board"],
    },
  ],

  faculty: [
    {
      id: 1,
      name: "Dr. Sarah Johnson",
      designation: "Professor",
      department: "Computer Science",
      email: "sarah.johnson@university.edu",
      phone: "+1-555-0101",
      specializations: ["Data Structures", "Algorithms", "Programming", "Software Engineering"],
      maxHoursPerWeek: 18,
      subjects: ["Data Structures", "Algorithms", "Programming"],
    },
    {
      id: 2,
      name: "Prof. Michael Chen",
      designation: "Associate Professor",
      department: "Computer Science",
      email: "michael.chen@university.edu",
      phone: "+1-555-0102",
      specializations: ["Database Systems", "Software Engineering", "Web Development"],
      maxHoursPerWeek: 16,
      subjects: ["Database Systems", "Software Engineering"],
    },
    {
      id: 3,
      name: "Dr. Emily Rodriguez",
      designation: "Professor",
      department: "Mathematics",
      email: "emily.rodriguez@university.edu",
      phone: "+1-555-0103",
      specializations: ["Mathematics", "Statistics", "Calculus", "Linear Algebra"],
      maxHoursPerWeek: 20,
      subjects: ["Mathematics", "Statistics", "Calculus"],
    },
    {
      id: 4,
      name: "Prof. David Wilson",
      designation: "Associate Professor",
      department: "Physics",
      email: "david.wilson@university.edu",
      phone: "+1-555-0104",
      specializations: ["Physics", "Electronics", "Circuit Analysis", "Quantum Mechanics"],
      maxHoursPerWeek: 18,
      subjects: ["Physics", "Electronics", "Circuit Analysis"],
    },
    {
      id: 5,
      name: "Dr. Lisa Thompson",
      designation: "Assistant Professor",
      department: "English",
      email: "lisa.thompson@university.edu",
      phone: "+1-555-0105",
      specializations: ["English Literature", "Communication Skills", "Creative Writing"],
      maxHoursPerWeek: 15,
      subjects: ["English Literature", "Communication Skills"],
    },
    {
      id: 6,
      name: "Prof. James Anderson",
      designation: "Professor",
      department: "Computer Science",
      email: "james.anderson@university.edu",
      phone: "+1-555-0106",
      specializations: ["Machine Learning", "Artificial Intelligence", "Data Mining", "Deep Learning"],
      maxHoursPerWeek: 20,
      subjects: ["Machine Learning", "Artificial Intelligence", "Data Mining"],
    },
    {
      id: 7,
      name: "Dr. Maria Garcia",
      designation: "Assistant Professor",
      department: "Chemistry",
      email: "maria.garcia@university.edu",
      phone: "+1-555-0107",
      specializations: ["Organic Chemistry", "Analytical Chemistry", "Biochemistry"],
      maxHoursPerWeek: 16,
      subjects: ["Chemistry", "Organic Chemistry"],
    },
    {
      id: 8,
      name: "Prof. Robert Kim",
      designation: "Lecturer",
      department: "Business",
      email: "robert.kim@university.edu",
      phone: "+1-555-0108",
      specializations: ["Business Management", "Marketing", "Finance"],
      maxHoursPerWeek: 14,
      subjects: ["Business Management", "Marketing"],
    },
  ],

  subjects: [
    {
      id: 1,
      name: "Data Structures",
      code: "CS201",
      hoursPerWeek: 4,
      type: "Theory",
      department: "Computer Science",
      credits: 3,
      semester: 3,
    },
    {
      id: 2,
      name: "Database Lab",
      code: "CS202L",
      hoursPerWeek: 3,
      type: "Lab",
      department: "Computer Science",
      credits: 2,
      semester: 3,
    },
    {
      id: 3,
      name: "Mathematics III",
      code: "MA301",
      hoursPerWeek: 5,
      type: "Theory",
      department: "Mathematics",
      credits: 4,
      semester: 3,
    },
    {
      id: 4,
      name: "Physics Lab",
      code: "PH201L",
      hoursPerWeek: 2,
      type: "Lab",
      department: "Physics",
      credits: 1,
      semester: 2,
    },
    {
      id: 5,
      name: "Software Engineering",
      code: "CS301",
      hoursPerWeek: 4,
      type: "Theory",
      department: "Computer Science",
      credits: 3,
      semester: 3,
    },
    {
      id: 6,
      name: "Communication Skills",
      code: "EN101",
      hoursPerWeek: 2,
      type: "Tutorial",
      department: "English",
      credits: 2,
      semester: 1,
    },
    {
      id: 7,
      name: "Machine Learning",
      code: "CS401",
      hoursPerWeek: 4,
      type: "Theory",
      department: "Computer Science",
      credits: 3,
      semester: 4,
    },
    {
      id: 8,
      name: "Electronics Lab",
      code: "EC201L",
      hoursPerWeek: 3,
      type: "Lab",
      department: "Electronics",
      credits: 2,
      semester: 2,
    },
    {
      id: 9,
      name: "Algorithms",
      code: "CS202",
      hoursPerWeek: 4,
      type: "Theory",
      department: "Computer Science",
      credits: 3,
      semester: 3,
    },
    {
      id: 10,
      name: "Statistics",
      code: "MA201",
      hoursPerWeek: 3,
      type: "Theory",
      department: "Mathematics",
      credits: 3,
      semester: 2,
    },
    {
      id: 11,
      name: "Organic Chemistry",
      code: "CH301",
      hoursPerWeek: 4,
      type: "Theory",
      department: "Chemistry",
      credits: 3,
      semester: 3,
    },
    {
      id: 12,
      name: "Business Management",
      code: "BM101",
      hoursPerWeek: 3,
      type: "Theory",
      department: "Business",
      credits: 3,
      semester: 1,
    },
  ],

  basicData: {
    totalClassrooms: 24,
    totalBatches: 12,
    totalSubjects: 45,
    maxClassesPerDay: 8,
    semester: 3,
    academicYear: "2024-25",
  },
}
